version: "2"

plugins:
  checkstyle:
    enabled: true
    config: etc/checkstyle.xml
  pmd:
    enabled: true
    config: etc/pmd.xml
  sonar-java:
    enabled: true
  shellcheck:
    enabled: true

exclude_patterns:
  - .github/
  - .run/
  - etc/

