version: "2"

plugins:
  checkstyle:
    enabled: true
#    config: "etc/google_checkstyle.xml"
#      file: "etc/google_checkstyle.xml"
  pmd:
    enabled: true
  sonar-java:
    enabled: true
  shellcheck:
    enabled: true

