version: "2"

plugins:
  checkstyle:
    enabled: true
    config: etc/codeclimate_checkstyle.xml
  pmd:
    enabled: true
    config:
      rules:
        - java-basic
        - java-empty
        - java-imports
        - java-unnecessary
        - java-unusedcode
  sonar-java:
    enabled: true
  shellcheck:
    enabled: true

exclude_patterns:
  - .github/
  - .run/
  - etc/

