version: '3.8'
services:
  app:
    image: ${APP_IMAGE}
    depends_on:
      - postgres
    networks:
      dev_network:
        aliases: [app]
    ports:
      - 8080:8080
    environment:
      - spring_datasource_url=jdbc:postgresql://database:5432/dev
