services:
  app:
    build: .
    depends_on:
      - postgres
    networks:
      dev_network:
        aliases: [app]
    ports:
      - 8080:8080
    environment:
      - spring_datasource_url=jdbc:postgresql://database:5432/postgres
