# Loggers
logging.level:
  root: WARN

# Web
spring.jackson.default-property-inclusion: NON_NULL

# Database
spring:
  liquibase.change-log: liquibase-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    properties.hibernate:
      jdbc.batch_size: 5

---
spring.config.activate.on-profile: dev

# Loggers
logging.level:
  com.github.mwierzchowski: DEBUG

# Actuator
management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always
