# Application info
info.app:
  name: @project.name@
  description: @project.description@

# Loggers
logging.level:
  root: WARN
  @project.groupId@: DEBUG

# Actuator
management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always

# Database
spring:
  liquibase.change-log: liquibase-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    properties.hibernate:
      jdbc.batch_size: 5
      format_sql: true
  show-sql: true

# Web
spring.jackson.default-property-inclusion: NON_NULL