services:
  postgres:
    image: postgres:13.1-alpine
    networks:
      dev_network:
        aliases: [database]
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database_data:/var/lib/postgresql/data

  pg-admin4:
    image: dpage/pgadmin4:6.7
    networks:
      dev_network:
    ports:
      - 81:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin4.json:/pgadmin4/servers.json:ro

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - 83:8080
    environment:
      - URL=http://localhost:8080/v3/api-docs

volumes:
  database_data:
  pgadmin_data:

networks:
  dev_network: