name: Integration
on: push
env:
  BUILD_TAG: ghcr.io/${{ github.REPOSITORY }}:rc.${{ github.RUN_NUMBER }}

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up build
        uses: s4u/setup-maven-action@v1.3.1
        with:
          java-version: '17'
          java-distribution: 'temurin'
          maven-version: 3.8.4

      - name: Run tests
        run: mvn jacoco:prepare-agent verify surefire-report:report-only jacoco:report

      - name: Publish test report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test report
          path: ${{ github.WORKSPACE }}/target/site/surefire-report.html

      - name: Export test coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          JACOCO_SOURCE_PATH: ${{ github.WORKSPACE }}/src/main/java
        with:
          coverageLocations: ${{ github.WORKSPACE }}/target/site/jacoco/jacoco.xml:jacoco

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ github.REPOSITORY_OWNER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.BUILD_TAG }}
          cache-from: type=gha,scope=${{ github.WORKFLOW }}
          cache-to: type=gha,scope=${{ github.WORKFLOW }}

  Api-Test:
    name: API Test
    runs-on: ubuntu-latest
    needs:
      - Test
      - Build
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download image
        run: docker pull ${{ env.BUILD_TAG }}

      - name: Load image
        run:  docker image ls -a



